import type { Customer } from './types';

export const mockCustomers: Customer[] = [
  {
    id: 'BU79786',
    state: 'Washington',
    response: 'No',
    coverage: 'Basic',
    education: 'Bachelor',
    employmentStatus: 'Employed',
    gender: 'Female',
    income: 56274,
    locationCode: 'Suburban',
    maritalStatus: 'Married',
    monthlyPremiumAuto: 69,
    monthsSinceLastClaim: 32,
    monthsSincePolicyInception: 5,
    numberOfOpenComplaints: 0,
    numberOfPolicies: 1,
    policyType: 'Corporate Auto',
    policy: 'Corporate L3',
    renewOfferType: 'Offer1',
    salesChannel: 'Agent',
    totalClaimAmount: 384.81,
    vehicleClass: 'Two-Door Car',
    vehicleSize: 'Medsize',
    segment: 'Newcomer',
    clvData: {
      clvEstimate: 2763.52,
      confidenceInterval: [2500, 3000],
      recency: 32,
      frequency: 1,
      monetary: 69,
      purchaseProbability: 0.6,
      expectedPurchases: 2,
      shapValues: [
        { feature: 'Income', value: 0.3 },
        { feature: 'Months Since Policy Inception', value: 0.2 },
        { feature: 'Monthly Premium', value: 0.25 },
        { feature: 'Months Since Last Claim', value: -0.15 },
      ],
    },
  },
  {
    id: 'QZ44356',
    state: 'Arizona',
    response: 'No',
    coverage: 'Extended',
    education: 'Bachelor',
    employmentStatus: 'Unemployed',
    gender: 'Female',
    income: 0,
    locationCode: 'Suburban',
    maritalStatus: 'Single',
    monthlyPremiumAuto: 94,
    monthsSinceLastClaim: 13,
    monthsSincePolicyInception: 42,
    numberOfOpenComplaints: 0,
    numberOfPolicies: 8,
    policyType: 'Personal Auto',
    policy: 'Personal L3',
    renewOfferType: 'Offer3',
    salesChannel: 'Agent',
    totalClaimAmount: 655.2,
    vehicleClass: 'Four-Door Car',
    vehicleSize: 'Medsize',
    segment: 'Champion',
    clvData: {
      clvEstimate: 6979.54,
      confidenceInterval: [6500, 7500],
      recency: 13,
      frequency: 8,
      monetary: 94,
      purchaseProbability: 0.95,
      expectedPurchases: 5,
      shapValues: [
        { feature: 'Number of Policies', value: 0.6 },
        { feature: 'Months Since Policy Inception', value: 0.25 },
        { feature: 'Months Since Last Claim', value: -0.05 },
        { feature: 'Coverage (Extended)', value: 0.2 },
      ],
    },
  },
  {
    id: 'AI49188',
    state: 'Nevada',
    response: 'No',
    coverage: 'Premium',
    education: 'College',
    employmentStatus: 'Employed',
    gender: 'Female',
    income: 48767,
    locationCode: 'Suburban',
    maritalStatus: 'Married',
    monthlyPremiumAuto: 108,
    monthsSinceLastClaim: 18,
    monthsSincePolicyInception: 38,
    numberOfOpenComplaints: 0,
    numberOfPolicies: 2,
    policyType: 'Personal Auto',
    policy: 'Personal L3',
    renewOfferType: 'Offer1',
    salesChannel: 'Agent',
    totalClaimAmount: 566.4,
    vehicleClass: 'Two-Door Car',
    vehicleSize: 'Medsize',
    segment: 'Loyal',
    clvData: {
      clvEstimate: 12965.6,
      confidenceInterval: [12000, 14000],
      recency: 18,
      frequency: 2,
      monetary: 108,
      purchaseProbability: 0.88,
      expectedPurchases: 4,
      shapValues: [
        { feature: 'Monthly Premium', value: 0.5 },
        { feature: 'Coverage (Premium)', value: 0.3 },
        { feature: 'Income', value: 0.15 },
        { feature: 'Months Since Last Claim', value: -0.1 },
      ],
    },
  },
];
